# Generated by Django 5.1.7 on 2025-03-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsApp', '0002_alter_doctors_phone_alter_patients_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
