# Generated by Django 5.1.7 on 2025-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsApp', '0004_alter_patients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
